ALTER TABLE "account" DROP COLUMN IF EXISTS name;
ALTER TABLE "account" DROP COLUMN IF EXISTS last_name;
ALTER TABLE "account" DROP COLUMN IF EXISTS email;
ALTER TABLE "account" DROP COLUMN IF EXISTS password;
